name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Setup Git
        run: |
          git config user.name 'Willin Wang'
          git config user.email 'willin@willin.org'
      - name: bump version
        run: npm version ${{ github.event.inputs.version }}
      - name: Push latest version
        run: git push origin main --follow-tags
